version: '3'

networks:
  laravel:

services:
  nginx1:
    image: nginx:stable-alpine
    container_name: nginx1
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php1
    volumes:
      - ./src:/var/www/html
    ports:
      -   "9000:9000"
    networks:
      - laravel
